run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - ineffassign
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-dirs:
    - vendor
    - build
    - tmp

  exclude-rules:
    - path: ^wnc/client_test\.go$
      linters: [errcheck]
    - path: ^internal/tests/helpers_test\.go$
      linters: [errcheck]
