#!/usr/bin/env bash

# @meta version 1.0.0
# @meta author "@umatare5"
# @describe List filterable fields and values from YANG model data

# @option -m --model <MODEL>          YANG model name (required)
# @option -s --statement <STATEMENT>  YANG statement name (required)
# @option    --filter <FILTER>        Filter expression (e.g., "wlan-id=1", "profile-name=labo2")
# @option -c --controller <HOST>      WNC controller hostname or IP (required unless WNC_CONTROLLER set)
# @option -t --token <TOKEN>          Basic auth token (or use WNC_ACCESS_TOKEN env var)
# @option -p --protocol <PROTOCOL>    Protocol: http or https [default: https] [choices: http,https]
# @option -f --format <FORMAT>        Output format: table or json [default: table] [choices: table,json]
# @flag   -k --insecure               Skip TLS certificate verification
# @flag   -v --verbose                Enable verbose output
# @flag      --no-color               Disable colored output

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR

# Source bootstrap library
source "${SCRIPT_DIR}/lib/bootstrap.sh"

# Initialize libraries and load module
init_wnc_libraries "${SCRIPT_DIR}/lib/get_yang_model_filters"

# Validate required CLI tools
validate_required_cli_tools "strict"

# Entrypoint: extract filterable fields and values
main() {
    # shellcheck disable=SC2154  # argc variables are generated by argc
    local statement_name="${argc_statement}"
    local controller="${argc_controller:-${WNC_CONTROLLER:-}}"
    local token="${argc_token:-${WNC_ACCESS_TOKEN:-}}"
    local protocol="${argc_protocol:-https}"
    local insecure="${argc_insecure:-false}"
    local output_format="${argc_format:-table}"

    run_yang_filter_extraction "" "${statement_name}" \
        "$controller" "$token" "$protocol" "$insecure" "$output_format"
}

eval "$(argc --argc-eval "$0" "$@")"
