name: actionlint

on:
  push:
    branches: ["main"]
    paths: [".github/workflows/**"]
  pull_request:
    branches: ["main"]
    paths: [".github/workflows/**"]

permissions:
  contents: read

jobs:
  actionlint:
    uses: umatare5/common/.github/workflows/actionlint.yml@c70780f0ddb98d15dbdc6b2a89cf01f766c65b7d # v0.9.0
