name: actionlint

on:
  push:
    branches: ["main"]
    paths: [".github/workflows/**"]
  pull_request:
    branches: ["main"]
    paths: [".github/workflows/**"]

permissions:
  contents: read

jobs:
  actionlint:
    uses: umatare5/common/.github/workflows/actionlint.yml@c398db4525f79997fd25bfb7b1f1292d236f7fce # v0.16.0
