name: Release Application

on:
  push:
    branches: ["main"]
    paths: ["VERSION"]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  tagging:
    uses: umatare5/common/.github/workflows/tagging.yml@c398db4525f79997fd25bfb7b1f1292d236f7fce # v0.16.0

  release:
    needs: [tagging]
    uses: umatare5/common/.github/workflows/go-release.yml@c398db4525f79997fd25bfb7b1f1292d236f7fce # v0.16.0
    with:
      go_version: "1.26.6"
      goreleaser_version: "v2.17.1"
