name: Release Application

on:
  push:
    branches: ["main"]
    paths: ["VERSION"]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  tagging:
    uses: umatare5/common/.github/workflows/tagging.yml@49d5d37a92af3d54a6aeb9e55b8ab40e3713343c # v0.10.0

  release:
    uses: umatare5/common/.github/workflows/go-release.yml@49d5d37a92af3d54a6aeb9e55b8ab40e3713343c # v0.10.0
    with:
      go_version: "1.24.5"
      goreleaser_version: "v2.11.1"
