name: Release Application

on:
  push:
    branches: ["main"]
    paths: ["VERSION"]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  tagging:
    uses: umatare5/common/.github/workflows/tagging.yml@d2ecc6dad30688e2c0bd5676d741c359194e23a7 # v0.11.0

  release:
    uses: umatare5/common/.github/workflows/go-release.yml@d2ecc6dad30688e2c0bd5676d741c359194e23a7 # v0.11.0
    with:
      go_version: "1.24.5"
      goreleaser_version: "v2.11.1"
