name: Format and Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  fmt:
    uses: umatare5/common/.github/workflows/go-test-fmt.yml@c398db4525f79997fd25bfb7b1f1292d236f7fce # v0.16.0
    with:
      go_version: "1.26.6"
      golangci_lint_version: "v2.12.2"
      golangci_lint_config: ".golangci.yml"
