name: Test and Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 2 * * 1" # every Monday at 2:00

permissions:
  contents: read

jobs:
  build:
    uses: umatare5/common/.github/workflows/go-test-build.yml@c398db4525f79997fd25bfb7b1f1292d236f7fce # v0.16.0
    with:
      go_version: "1.26.6"
      skip_build: true
